### ISSUE TITLE
issue merging counts files

### ISSUE THREAD

**Issue by sb43** [cancerit/cgp-convert-counts#7]
python ~/scripts/cgp-convert-counts/scripts/merge_samples.py -g ensembl_grch37_build_75_genelength_2_09_2019.txt --merge_ext count_count_fpkm_tpm.tsv.gz --input_path out_fpkm_02_09_2019

Merging val unfiltered_count for samples into a single file....: 
Traceback (most recent call last):
  File "/nfs/users/nfs_s/sb43/scripts/cgp-convert-counts/scripts/merge_samples.py", line 115, in <module>
    main()
  File "/nfs/users/nfs_s/sb43/scripts/cgp-convert-counts/scripts/merge_samples.py", line 112, in main
    merge_files(type, **vars(opts))
  File "/nfs/users/nfs_s/sb43/scripts/cgp-convert-counts/scripts/merge_samples.py", line 50, in merge_files
    for line in sample_counts:
  File "/nfs/users/nfs_s/sb43/scripts/helperscripts/env/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by sb43** [comment]
Workaround is to provide uncompressed input data, before we fix merge_samples.py to handle gzip input

**Comment by keiranmraine** [comment]
@sb43 does this affect only manual use or the pipeline also?

**Comment by sb43** [comment]
@keiranmraine No issues with pipeline as we don't merge sample level data to generate project level consolidated  file in our pipeline.
